package com.lukaszjag.diet_tracker_android.tools.sql_tools;

public class QueryMaker {
    public static String getAllProductTableLikeProductNameCaseInsensitive(String productData) {
        String escapedData = productData != null ? productData.replace("'", "''") : "";
        return "SELECT * FROM [diet_tracker_schema].[product_table] WHERE LOWER(product_name) LIKE '%" + escapedData + "%'";
    }

    public static String getAllProductsFromCalendarTableLikeDate(String date) {
        String escapedDate = date != null ? date.replace("'", "''") : "";
        return "SELECT * FROM [diet_tracker_schema].[calendar] WHERE day_date LIKE '%" + escapedDate + "%'";
    }

    // --- NEW METHODS FOR NOTES ---

    public static String getAllNotesQuery() {
        return "SELECT * FROM [diet_tracker_schema].[notes]";
    }

    public static String insertNoteQuery(String title, String subtitle, String description, String category,
                                         boolean isUrgently, boolean isLearning, boolean isGeneral,
                                         boolean isToday, boolean isToBuy, String created, String deadline) {

        // Helper to format strings
        autoFormat(title);

        return "INSERT INTO [diet_tracker_schema].[notes] " +
                "([title], [subtitle], [description], [category], [is_urgently], [is_learning], " +
                "[is_general_to_do], [is_today_task], [is_to_buy_task], [date_created], [date_deadline]) " +
                "VALUES (" +
                "N'" + title.replace("'", "''") + "', " +
                "N'" + subtitle.replace("'", "''") + "', " +
                "N'" + description.replace("'", "''") + "', " +
                "N'" + category.replace("'", "''") + "', " +
                (isUrgently ? 1 : 0) + ", " +
                (isLearning ? 1 : 0) + ", " +
                (isGeneral ? 1 : 0) + ", " +
                (isToday ? 1 : 0) + ", " +
                (isToBuy ? 1 : 0) + ", " +
                "'" + created + "', " +
                (deadline == null || deadline.isEmpty() ? "NULL" : "'" + deadline + "'") +
                ");";
    }

    private static String autoFormat(String val) {
        return val == null ? "" : val;
    }

    public static String insertMealToCalendarTable(
            String dayDate, String dayName, String mealName, double amountOfProduct,
            String productName, double kcal, double protein, double fat, double carbs,
            String timeOptional, String commentOptional, double kcalConsume,
            double carbsConsume, double fatConsume, double proteinConsume) {

        String autoGeneratedId = java.util.UUID.randomUUID().toString();

        return insertMealToCalendarTable(
                dayDate, dayName, mealName, amountOfProduct, productName,
                kcal, protein, fat, carbs, timeOptional, commentOptional,
                kcalConsume, carbsConsume, fatConsume, proteinConsume,
                autoGeneratedId
        );
    }

    public static String insertMealToCalendarTable(
            String dayDate, String dayName, String mealName, double amountOfProduct,
            String productName, double kcal, double protein, double fat, double carbs,
            String timeOptional, String commentOptional, double kcalConsume,
            double carbsConsume, double fatConsume, double proteinConsume,
            String rowId) {

        String sqlDayDate = (dayDate == null || dayDate.trim().isEmpty())
                ? "NULL" : "'" + dayDate.replace("'", "''") + "'";

        String sqlDayName = (dayName == null || dayName.trim().isEmpty())
                ? "NULL" : "'" + dayName.replace("'", "''") + "'";

        String sqlMealName = (mealName == null || mealName.trim().isEmpty())
                ? "NULL" : "'" + mealName.replace("'", "''") + "'";

        String sqlProductName = (productName == null || productName.trim().isEmpty())
                ? "NULL" : "'" + productName.replace("'", "''") + "'";

        String sqlTime = (timeOptional == null || timeOptional.equalsIgnoreCase("none") || timeOptional.trim().isEmpty())
                ? "NULL" : "'" + timeOptional.replace("'", "''") + "'";

        String sqlComment = (commentOptional == null || commentOptional.equalsIgnoreCase("none") || commentOptional.trim().isEmpty())
                ? "NULL" : "'" + commentOptional.replace("'", "''") + "'";

        String sqlRowId = (rowId == null || rowId.trim().isEmpty())
                ? "NULL" : "'" + rowId.replace("'", "''") + "'";

        return "INSERT INTO [diet_tracker_schema].[calendar]\n" +
                "([day_date], [day_name], [meal_name], [amount_of_product], [product_name],\n" +
                "[kcal], [protein], [fat], [carbs], [time_optional], [comment_optional],\n" +
                "[kcal_consume], [carbs_consume], [fat_consume], [protein_consume], [row_id])\n" +
                "VALUES (\n" +
                sqlDayDate + ",\n" +
                sqlMealName + ",\n" +
                sqlProductName + ",\n" +
                kcal + ",\n" +
                protein + ",\n" +
                fat + ",\n" +
                carbs + ",\n" +
                sqlTime + ",\n" +
                sqlComment + ",\n" +
                kcalConsume + ",\n" +
                carbsConsume + ",\n" +
                fatConsume + ",\n" +
                proteinConsume + ",\n" +
                sqlRowId + "\n" +
                ");\n" +
                "SELECT 1 AS success;";
    }
}